name: schedule
on:
  schedule:
    - cron: '40 9 * * *'
jobs:
  create_sprint:
    name: hello
    runs-on: ubuntu-latest
    steps:
    - name: cron hello
      run: |
        echo 'Hello, My Cron Job!'
